// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.CreateDataExport;
using AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DeleteDataExport;
using AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.GetDataExport;
using AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.GetDataExports;
using AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.UpdateDataExport;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.DataExports
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\data-exports
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataExportsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateDataExport property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.CreateDataExport.CreateDataExportRequestBuilder CreateDataExport
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.CreateDataExport.CreateDataExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteDataExport property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DeleteDataExport.DeleteDataExportRequestBuilder DeleteDataExport
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DeleteDataExport.DeleteDataExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetDataExport property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.GetDataExport.GetDataExportRequestBuilder GetDataExport
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.GetDataExport.GetDataExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetDataExports property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.GetDataExports.GetDataExportsRequestBuilder GetDataExports
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.GetDataExports.GetDataExportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateDataExport property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.UpdateDataExport.UpdateDataExportRequestBuilder UpdateDataExport
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.UpdateDataExport.UpdateDataExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DataExportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataExportsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-exports", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DataExportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataExportsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/data-exports", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
