// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Admin.CreateAdminAccount;
using AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount;
using AppBlueprint.Api.Client.Sdk.Api.V1.Admin.GetAdminAccount;
using AppBlueprint.Api.Client.Sdk.Api.V1.Admin.GetAdminAccounts;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Admin
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\admin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdminRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateAdminAccount property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.CreateAdminAccount.CreateAdminAccountRequestBuilder CreateAdminAccount
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.CreateAdminAccount.CreateAdminAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteAdminAccount property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.DeleteAdminAccountRequestBuilder DeleteAdminAccount
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.DeleteAdminAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAdminAccount property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.GetAdminAccount.GetAdminAccountRequestBuilder GetAdminAccount
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.GetAdminAccount.GetAdminAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAdminAccounts property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.GetAdminAccounts.GetAdminAccountsRequestBuilder GetAdminAccounts
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.GetAdminAccounts.GetAdminAccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/admin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/admin", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
