apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura
  name: hasura-loadbalancer-svc
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hasura
  type: LoadBalancer