name: Report a bug
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info (leave empty if we should use your GitHub profile)?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed description?
      description: Also tell us more about the bug, and what you were expecting.
      value: |
        **Describe the bug**
        A clear and concise description of the bug.

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Additional context**
        Add any other context about the problem here.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      multiple: false
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: checkboxes
    id: security-related
    attributes:
      label: Is this bug security related?
      description: Please let us know if this bug is security related. If so please consider using our [Report a security vulnerability](../security/advisories/new) form instead.
      options:
        - label: This bug is related to security
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true