// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Presentation.Ui.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PhoneNumberEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contactPerson property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.ContactPersonEntity? ContactPerson { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.ContactPersonEntity ContactPerson { get; set; }
#endif
        /// <summary>The countryCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.CustomerEntity? Customer { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.CustomerEntity Customer { get; set; }
#endif
        /// <summary>The customerId property</summary>
        public int? CustomerId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isPrimary property</summary>
        public bool? IsPrimary { get; set; }
        /// <summary>The isVerified property</summary>
        public bool? IsVerified { get; set; }
        /// <summary>The lastUpdatedAt property</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The tenant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity? Tenant { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity Tenant { get; set; }
#endif
        /// <summary>The tenantId property</summary>
        public int? TenantId { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity? User { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity User { get; set; }
#endif
        /// <summary>The userId property</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.PhoneNumberEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.PhoneNumberEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.PhoneNumberEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contactPerson", n => { ContactPerson = n.GetObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.ContactPersonEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.ContactPersonEntity.CreateFromDiscriminatorValue); } },
                { "countryCode", n => { CountryCode = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customer", n => { Customer = n.GetObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.CustomerEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.CustomerEntity.CreateFromDiscriminatorValue); } },
                { "customerId", n => { CustomerId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isPrimary", n => { IsPrimary = n.GetBoolValue(); } },
                { "isVerified", n => { IsVerified = n.GetBoolValue(); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "tenant", n => { Tenant = n.GetObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity.CreateFromDiscriminatorValue); } },
                { "tenantId", n => { TenantId = n.GetIntValue(); } },
                { "user", n => { User = n.GetObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.ContactPersonEntity>("contactPerson", ContactPerson);
            writer.WriteStringValue("countryCode", CountryCode);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.CustomerEntity>("customer", Customer);
            writer.WriteIntValue("customerId", CustomerId);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isPrimary", IsPrimary);
            writer.WriteBoolValue("isVerified", IsVerified);
            writer.WriteDateTimeOffsetValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteStringValue("number", Number);
            writer.WriteObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity>("tenant", Tenant);
            writer.WriteIntValue("tenantId", TenantId);
            writer.WriteObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity>("user", User);
            writer.WriteIntValue("userId", UserId);
        }
    }
}
#pragma warning restore CS0618
