// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Presentation.Ui.Sdk.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TeamEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The lastUpdatedAt property</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity? Owner { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity Owner { get; set; }
#endif
        /// <summary>The teamInvites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamInviteEntity>? TeamInvites { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamInviteEntity> TeamInvites { get; set; }
#endif
        /// <summary>The teamMembers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamMemberEntity>? TeamMembers { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamMemberEntity> TeamMembers { get; set; }
#endif
        /// <summary>The tenant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity? Tenant { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity Tenant { get; set; }
#endif
        /// <summary>The tenantId property</summary>
        public int? TenantId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity.CreateFromDiscriminatorValue); } },
                { "teamInvites", n => { TeamInvites = n.GetCollectionOfObjectValues<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamInviteEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamInviteEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "teamMembers", n => { TeamMembers = n.GetCollectionOfObjectValues<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamMemberEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamMemberEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tenant", n => { Tenant = n.GetObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity>(global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity.CreateFromDiscriminatorValue); } },
                { "tenantId", n => { TenantId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteDateTimeOffsetValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.UserEntity>("owner", Owner);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamInviteEntity>("teamInvites", TeamInvites);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TeamMemberEntity>("teamMembers", TeamMembers);
            writer.WriteObjectValue<global::AppBlueprint.Presentation.Ui.Sdk.Client.Models.TenantEntity>("tenant", Tenant);
            writer.WriteIntValue("tenantId", TenantId);
        }
    }
}
#pragma warning restore CS0618
