// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.CreateApiKey;
using AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.DeleteApiKey;
using AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.GetApiKey;
using AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.GetApiKeys;
using AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.UpdateApiKey;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\api-keys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiKeysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateApiKey property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.CreateApiKey.CreateApiKeyRequestBuilder CreateApiKey
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.CreateApiKey.CreateApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteApiKey property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.DeleteApiKey.DeleteApiKeyRequestBuilder DeleteApiKey
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.DeleteApiKey.DeleteApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetApiKey property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.GetApiKey.GetApiKeyRequestBuilder GetApiKey
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.GetApiKey.GetApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetApiKeys property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.GetApiKeys.GetApiKeysRequestBuilder GetApiKeys
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.GetApiKeys.GetApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateApiKey property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.UpdateApiKey.UpdateApiKeyRequestBuilder UpdateApiKey
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.UpdateApiKey.UpdateApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.ApiKeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiKeysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/api-keys", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.ApiKeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiKeysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/api-keys", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
