// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.Integrations.CreateIntegration;
using AppBlueprint.Api.Client.Sdk.Api.Integrations.DeleteIntegration;
using AppBlueprint.Api.Client.Sdk.Api.Integrations.GetIntegration;
using AppBlueprint.Api.Client.Sdk.Api.Integrations.GetIntegrations;
using AppBlueprint.Api.Client.Sdk.Api.Integrations.UpdateIntegration;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.Integrations
{
    /// <summary>
    /// Builds and executes requests for operations under \api\integrations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntegrationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateIntegration property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Integrations.CreateIntegration.CreateIntegrationRequestBuilder CreateIntegration
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Integrations.CreateIntegration.CreateIntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteIntegration property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Integrations.DeleteIntegration.DeleteIntegrationRequestBuilder DeleteIntegration
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Integrations.DeleteIntegration.DeleteIntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetIntegration property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Integrations.GetIntegration.GetIntegrationRequestBuilder GetIntegration
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Integrations.GetIntegration.GetIntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetIntegrations property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Integrations.GetIntegrations.GetIntegrationsRequestBuilder GetIntegrations
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Integrations.GetIntegrations.GetIntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateIntegration property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Integrations.UpdateIntegration.UpdateIntegrationRequestBuilder UpdateIntegration
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Integrations.UpdateIntegration.UpdateIntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.Integrations.IntegrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegrationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/integrations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.Integrations.IntegrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegrationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/integrations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
