// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Team.CreateTeam;
using AppBlueprint.Api.Client.Sdk.Api.V1.Team.DeleteTeam;
using AppBlueprint.Api.Client.Sdk.Api.V1.Team.GetTeam;
using AppBlueprint.Api.Client.Sdk.Api.V1.Team.GetTeams;
using AppBlueprint.Api.Client.Sdk.Api.V1.Team.UpdateTeam;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Team
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\team
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TeamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateTeam property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.CreateTeam.CreateTeamRequestBuilder CreateTeam
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.CreateTeam.CreateTeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteTeam property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.DeleteTeam.DeleteTeamRequestBuilder DeleteTeam
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.DeleteTeam.DeleteTeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetTeam property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.GetTeam.GetTeamRequestBuilder GetTeam
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.GetTeam.GetTeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetTeams property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.GetTeams.GetTeamsRequestBuilder GetTeams
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.GetTeams.GetTeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateTeam property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.UpdateTeam.UpdateTeamRequestBuilder UpdateTeam
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.UpdateTeam.UpdateTeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.TeamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/team", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.TeamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/team", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
