using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppBlueprint.Infrastructure.DatabaseContexts.Baseline.Migrations;

/// <inheritdoc />
public partial class UpdatePaymentProviderToBaseEntity : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        ArgumentNullException.ThrowIfNull(migrationBuilder);

        migrationBuilder.AlterColumn<DateTime>(
            name: "LastUpdatedAt",
            table: "PaymentProviders",
            type: "timestamp with time zone",
            nullable: true,
            oldClrType: typeof(DateTime),
            oldType: "timestamp with time zone",
            oldNullable: true,
            oldComment: "Timestamp when the payment provider was last updated");

        migrationBuilder.AlterColumn<DateTime>(
            name: "CreatedAt",
            table: "PaymentProviders",
            type: "timestamp with time zone",
            nullable: false,
            oldClrType: typeof(DateTime),
            oldType: "timestamp with time zone",
            oldDefaultValueSql: "CURRENT_TIMESTAMP",
            oldComment: "Timestamp when the payment provider was created");

        // Drop identity and change column type manually to avoid EF generating invalid DROP IDENTITY
        migrationBuilder.Sql(@"
                ALTER TABLE ""PaymentProviders"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;
                ALTER TABLE ""PaymentProviders"" ALTER COLUMN ""Id"" TYPE character varying(40);
            ");

        migrationBuilder.AddColumn<bool>(
            name: "IsSoftDeleted",
            table: "PaymentProviders",
            type: "boolean",
            nullable: false,
            defaultValue: false);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        ArgumentNullException.ThrowIfNull(migrationBuilder);

        migrationBuilder.DropColumn(
            name: "IsSoftDeleted",
            table: "PaymentProviders");

        migrationBuilder.AlterColumn<DateTime>(
            name: "LastUpdatedAt",
            table: "PaymentProviders",
            type: "timestamp with time zone",
            nullable: true,
            comment: "Timestamp when the payment provider was last updated",
            oldClrType: typeof(DateTime),
            oldType: "timestamp with time zone",
            oldNullable: true);

        migrationBuilder.AlterColumn<DateTime>(
            name: "CreatedAt",
            table: "PaymentProviders",
            type: "timestamp with time zone",
            nullable: false,
            defaultValueSql: "CURRENT_TIMESTAMP",
            comment: "Timestamp when the payment provider was created",
            oldClrType: typeof(DateTime),
            oldType: "timestamp with time zone");

        migrationBuilder.AlterColumn<int>(
            name: "Id",
            table: "PaymentProviders",
            type: "integer",
            nullable: false,
            comment: "Unique identifier for the payment provider",
            oldClrType: typeof(string),
            oldType: "character varying(40)",
            oldMaxLength: 40)
            .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

        // Re-create identity after changing column type back to integer
        migrationBuilder.Sql(@"ALTER TABLE ""PaymentProviders"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
    }
}
