// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.Files.CreateFile;
using AppBlueprint.Api.Client.Sdk.Api.Files.DeleteFile;
using AppBlueprint.Api.Client.Sdk.Api.Files.GetFile;
using AppBlueprint.Api.Client.Sdk.Api.Files.GetFiles;
using AppBlueprint.Api.Client.Sdk.Api.Files.UpdateFile;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.Files
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Files
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateFile property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Files.CreateFile.CreateFileRequestBuilder CreateFile
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Files.CreateFile.CreateFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteFile property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Files.DeleteFile.DeleteFileRequestBuilder DeleteFile
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Files.DeleteFile.DeleteFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetFile property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Files.GetFile.GetFileRequestBuilder GetFile
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Files.GetFile.GetFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetFiles property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Files.GetFiles.GetFilesRequestBuilder GetFiles
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Files.GetFiles.GetFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateFile property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Files.UpdateFile.UpdateFileRequestBuilder UpdateFile
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Files.UpdateFile.UpdateFileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Files", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Files", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
