// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Organization.CreateOrganization;
using AppBlueprint.Api.Client.Sdk.Api.V1.Organization.DeleteOrganization;
using AppBlueprint.Api.Client.Sdk.Api.V1.Organization.GetOrganization;
using AppBlueprint.Api.Client.Sdk.Api.V1.Organization.GetOrganizations;
using AppBlueprint.Api.Client.Sdk.Api.V1.Organization.UpdateOrganization;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Organization
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\organization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateOrganization property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.CreateOrganization.CreateOrganizationRequestBuilder CreateOrganization
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.CreateOrganization.CreateOrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteOrganization property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.DeleteOrganization.DeleteOrganizationRequestBuilder DeleteOrganization
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.DeleteOrganization.DeleteOrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetOrganization property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.GetOrganization.GetOrganizationRequestBuilder GetOrganization
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.GetOrganization.GetOrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetOrganizations property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.GetOrganizations.GetOrganizationsRequestBuilder GetOrganizations
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.GetOrganizations.GetOrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateOrganization property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.UpdateOrganization.UpdateOrganizationRequestBuilder UpdateOrganization
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.UpdateOrganization.UpdateOrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/organization", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/organization", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
