CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory"
(
    "MigrationId"
    character
    varying
(
    150
) NOT NULL,
    "ProductVersion" character varying
(
    32
) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY
(
    "MigrationId"
)
    );

START TRANSACTION;

CREATE TABLE "AuditLogs"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "Action"     text                     NOT NULL,
    "NewValue"   text                     NOT NULL,
    "OldValue"   text                     NOT NULL,
    "ModifiedBy" text                     NOT NULL,
    "ModifiedAt" timestamp with time zone NOT NULL,
    "Category"   text                     NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "AuthorizationProviders"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          text                     NOT NULL,
    "IsActive"      boolean                  NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "LastUpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_AuthorizationProviders" PRIMARY KEY ("Id")
);

CREATE TABLE "Country"
(
    "Id"      integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"    text NOT NULL,
    "IsoCode" text NOT NULL,
    "CityId"  text NOT NULL,
    CONSTRAINT "PK_Country" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers"
(
    "Id"                            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"                          text    NOT NULL,
    "Email"                         text    NOT NULL,
    "CurrentlyAtOnboardingFlowStep" integer NOT NULL,
    "TenantId"                      integer NOT NULL,
    "StripeCustomerId"              text    NOT NULL,
    "StripeSubscriptionId"          text    NOT NULL,
    "VatId"                         text    NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "GlobalRegionModels"
(
    "Id"   integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_GlobalRegionModels" PRIMARY KEY ("Id")
);

CREATE TABLE "Integrations"
(
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"                  text                     NOT NULL,
    "ServiceName"           text                     NOT NULL,
    "Description"           text                     NOT NULL,
    "ApiKeySecretReference" text                     NOT NULL,
    "CreatedAt"             timestamp with time zone NOT NULL,
    "LastUpdatedAt"         timestamp with time zone NULL,
    CONSTRAINT "PK_Integrations" PRIMARY KEY ("Id")
);

CREATE TABLE "Languages"
(
    "Id"   integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
);

CREATE TABLE "PaymentProviderModels"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          text                     NOT NULL,
    "Description"   text                     NOT NULL,
    "IsActive"      boolean                  NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "LastUpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_PaymentProviderModels" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          text                     NOT NULL,
    "Description"   text                     NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "LastUpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Sessions"
(
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionKey"  text                     NOT NULL,
    "SessionData" text                     NOT NULL,
    "ExpireDate"  timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id")
);

CREATE TABLE "Users"
(
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName"    text                     NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "IsActive"    boolean                  NOT NULL,
    "CreatedAt"   timestamp with time zone NOT NULL,
    "LastLogin"   timestamp with time zone NOT NULL,
    "Language"    text                     NOT NULL,
    "Timezone"    timestamp with time zone NOT NULL,
    "FirstName"   text                     NOT NULL,
    "LastName"    text                     NOT NULL,
    "Email"       text                     NOT NULL,
    "Avatar"      text                     NOT NULL,
    "Slug"        text                     NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "CountryRegions"
(
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"      text    NOT NULL,
    "CountryId" integer NOT NULL,
    CONSTRAINT "PK_CountryRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CountryRegions_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE CASCADE
);

CREATE TABLE "State"
(
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"      text    NOT NULL,
    "IsoCode"   text    NOT NULL,
    "CountryId" integer NOT NULL,
    CONSTRAINT "PK_State" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_State_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tenants"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          text                     NOT NULL,
    "Description"   text                     NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "LastUpdatedAt" timestamp with time zone NULL,
    "Email"         text                     NOT NULL,
    "Phone"         text                     NOT NULL,
    "TenantGuid"    text                     NOT NULL,
    "Type"          text                     NOT NULL,
    "VatNumber"     text                     NOT NULL,
    "Country"       text                     NOT NULL,
    "CustomerId"    integer                  NOT NULL,
    "IsActive"      boolean                  NOT NULL,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tenants_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Permissions"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          text                     NOT NULL,
    "Description"   text                     NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "LastUpdatedAt" timestamp with time zone NULL,
    "RoleModelId"   integer NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Permissions_Roles_RoleModelId" FOREIGN KEY ("RoleModelId") REFERENCES "Roles" ("Id")
);

CREATE TABLE "Documents"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName"   text                     NOT NULL,
    "FilePath"   text                     NOT NULL,
    "CreatedAt"  timestamp with time zone NOT NULL,
    "UserId"     integer                  NOT NULL,
    "CustomerId" integer                  NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Documents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmailInviteModel"
(
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY,
    "Token"                text                     NOT NULL,
    "ReferredEmailAddress" text                     NOT NULL,
    "CreatedAt"            timestamp with time zone NOT NULL,
    "LastUpdatedAt"        timestamp with time zone NULL,
    "ExpireAt"             timestamp with time zone NOT NULL,
    "InviteIsUsed"         boolean                  NOT NULL,
    "UserModelId"          integer NULL,
    CONSTRAINT "PK_EmailInviteModel" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailInviteModel_Users_UserModelId" FOREIGN KEY ("UserModelId") REFERENCES "Users" ("Id")
);

CREATE TABLE "EmailVerificationModel"
(
    "Id"              integer GENERATED BY DEFAULT AS IDENTITY,
    "Token"           text                     NOT NULL,
    "CreatedAt"       timestamp with time zone NOT NULL,
    "LastUpdatedAt"   timestamp with time zone NULL,
    "ExpireAt"        timestamp with time zone NOT NULL,
    "HasBeenOpened"   boolean                  NOT NULL,
    "HasBeenVerified" boolean                  NOT NULL,
    "UserModelId"     integer NULL,
    CONSTRAINT "PK_EmailVerificationModel" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailVerificationModel_Users_UserModelId" FOREIGN KEY ("UserModelId") REFERENCES "Users" ("Id")
);

CREATE TABLE "Notifications"
(
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "Title"     text                     NOT NULL,
    "Message"   text                     NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead"    boolean                  NOT NULL,
    "UserId"    integer                  NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TeamModels"
(
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          text                     NOT NULL,
    "IsActive"      boolean                  NOT NULL,
    "Description"   text                     NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "LastUpdatedAt" timestamp with time zone NULL,
    "OwnerId"       integer                  NOT NULL,
    CONSTRAINT "PK_TeamModels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TeamModels_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles"
(
    "Id"     integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "City"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"       integer NOT NULL,
    "CountryId"  integer NOT NULL,
    "PostalCode" integer NOT NULL,
    "StateId"    integer NOT NULL,
    CONSTRAINT "PK_City" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_City_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_City_State_StateId" FOREIGN KEY ("StateId") REFERENCES "State" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactPersons"
(
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text    NOT NULL,
    "LastName"  text    NOT NULL,
    "TenantId"  integer NOT NULL,
    "IsActive"  boolean NOT NULL,
    "IsPrimary" boolean NOT NULL,
    CONSTRAINT "PK_ContactPersons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactPersons_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TeamInvites"
(
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "TeamId"    integer                  NOT NULL,
    "ExpireAt"  timestamp with time zone NOT NULL,
    "IsActive"  boolean                  NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId"    integer                  NOT NULL,
    CONSTRAINT "PK_TeamInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TeamInvites_TeamModels_TeamId" FOREIGN KEY ("TeamId") REFERENCES "TeamModels" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TeamInvites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TeamMembers"
(
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "Alias"       text    NOT NULL,
    "IsActive"    boolean NOT NULL,
    "UserId"      integer NOT NULL,
    "TeamModelId" integer NULL,
    CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TeamMembers_TeamModels_TeamModelId" FOREIGN KEY ("TeamModelId") REFERENCES "TeamModels" ("Id"),
    CONSTRAINT "FK_TeamMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StreetModel"
(
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"      text    NOT NULL,
    "CityId"    integer NOT NULL,
    "CountryId" integer NOT NULL,
    CONSTRAINT "PK_StreetModel" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StreetModel_City_CityId" FOREIGN KEY ("CityId") REFERENCES "City" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StreetModel_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Emails"
(
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY,
    "Address"              text    NOT NULL,
    "UserId"               integer NOT NULL,
    "CustomerId"           integer NULL,
    "TenantId"             integer NULL,
    "ContactPersonModelId" integer NULL,
    CONSTRAINT "PK_Emails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Emails_ContactPersons_ContactPersonModelId" FOREIGN KEY ("ContactPersonModelId") REFERENCES "ContactPersons" ("Id"),
    CONSTRAINT "FK_Emails_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
    CONSTRAINT "FK_Emails_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id"),
    CONSTRAINT "FK_Emails_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PhoneNumbers"
(
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY,
    "Number"               text                     NOT NULL,
    "IsPrimary"            boolean                  NOT NULL,
    "IsVerified"           boolean                  NOT NULL,
    "CreatedAt"            timestamp with time zone NOT NULL,
    "LastUpdatedAt"        timestamp with time zone NULL,
    "UserId"               integer                  NOT NULL,
    "CustomerId"           integer NULL,
    "TenantId"             integer NULL,
    "ContactPersonModelId" integer NULL,
    CONSTRAINT "PK_PhoneNumbers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhoneNumbers_ContactPersons_ContactPersonModelId" FOREIGN KEY ("ContactPersonModelId") REFERENCES "ContactPersons" ("Id"),
    CONSTRAINT "FK_PhoneNumbers_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
    CONSTRAINT "FK_PhoneNumbers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id"),
    CONSTRAINT "FK_PhoneNumbers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Addresses"
(
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY,
    "CityId"               integer NOT NULL,
    "StreetId"             integer NOT NULL,
    "IsPrimary"            boolean NOT NULL,
    "Longtitude"           text    NOT NULL,
    "Latitude"             text    NOT NULL,
    "Floor"                integer NOT NULL,
    "Type"                 text    NOT NULL,
    "Number"               text    NOT NULL,
    "CountryId"            integer NOT NULL,
    "ContactPersonModelId" integer NULL,
    "UserModelId"          integer NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_City_CityId" FOREIGN KEY ("CityId") REFERENCES "City" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Addresses_ContactPersons_ContactPersonModelId" FOREIGN KEY ("ContactPersonModelId") REFERENCES "ContactPersons" ("Id"),
    CONSTRAINT "FK_Addresses_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Addresses_StreetModel_StreetId" FOREIGN KEY ("StreetId") REFERENCES "StreetModel" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Addresses_Users_UserModelId" FOREIGN KEY ("UserModelId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_Addresses_CityId" ON "Addresses" ("CityId");

CREATE INDEX "IX_Addresses_ContactPersonModelId" ON "Addresses" ("ContactPersonModelId");

CREATE INDEX "IX_Addresses_CountryId" ON "Addresses" ("CountryId");

CREATE INDEX "IX_Addresses_StreetId" ON "Addresses" ("StreetId");

CREATE INDEX "IX_Addresses_UserModelId" ON "Addresses" ("UserModelId");

CREATE UNIQUE INDEX "IX_City_CountryId" ON "City" ("CountryId");

CREATE INDEX "IX_City_StateId" ON "City" ("StateId");

CREATE INDEX "IX_ContactPersons_TenantId" ON "ContactPersons" ("TenantId");

CREATE INDEX "IX_CountryRegions_CountryId" ON "CountryRegions" ("CountryId");

CREATE INDEX "IX_Documents_CustomerId" ON "Documents" ("CustomerId");

CREATE INDEX "IX_Documents_UserId" ON "Documents" ("UserId");

CREATE INDEX "IX_EmailInviteModel_UserModelId" ON "EmailInviteModel" ("UserModelId");

CREATE INDEX "IX_Emails_ContactPersonModelId" ON "Emails" ("ContactPersonModelId");

CREATE INDEX "IX_Emails_CustomerId" ON "Emails" ("CustomerId");

CREATE INDEX "IX_Emails_TenantId" ON "Emails" ("TenantId");

CREATE INDEX "IX_Emails_UserId" ON "Emails" ("UserId");

CREATE INDEX "IX_EmailVerificationModel_UserModelId" ON "EmailVerificationModel" ("UserModelId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_Permissions_RoleModelId" ON "Permissions" ("RoleModelId");

CREATE INDEX "IX_PhoneNumbers_ContactPersonModelId" ON "PhoneNumbers" ("ContactPersonModelId");

CREATE INDEX "IX_PhoneNumbers_CustomerId" ON "PhoneNumbers" ("CustomerId");

CREATE INDEX "IX_PhoneNumbers_TenantId" ON "PhoneNumbers" ("TenantId");

CREATE INDEX "IX_PhoneNumbers_UserId" ON "PhoneNumbers" ("UserId");

CREATE INDEX "IX_State_CountryId" ON "State" ("CountryId");

CREATE INDEX "IX_StreetModel_CityId" ON "StreetModel" ("CityId");

CREATE INDEX "IX_StreetModel_CountryId" ON "StreetModel" ("CountryId");

CREATE INDEX "IX_TeamInvites_TeamId" ON "TeamInvites" ("TeamId");

CREATE INDEX "IX_TeamInvites_UserId" ON "TeamInvites" ("UserId");

CREATE INDEX "IX_TeamMembers_TeamModelId" ON "TeamMembers" ("TeamModelId");

CREATE INDEX "IX_TeamMembers_UserId" ON "TeamMembers" ("UserId");

CREATE INDEX "IX_TeamModels_OwnerId" ON "TeamModels" ("OwnerId");

CREATE INDEX "IX_Tenants_CustomerId" ON "Tenants" ("CustomerId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "IX_UserRoles_UserId" ON "UserRoles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230618134818_Initial', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "PaymentProviderModels" DROP CONSTRAINT "PK_PaymentProviderModels";

ALTER TABLE "GlobalRegionModels" DROP CONSTRAINT "PK_GlobalRegionModels";

ALTER TABLE "PaymentProviderModels" RENAME TO "PaymentProviders";

ALTER TABLE "GlobalRegionModels" RENAME TO "GlobalRegions";

ALTER TABLE "PaymentProviders"
    ADD CONSTRAINT "PK_PaymentProviders" PRIMARY KEY ("Id");

ALTER TABLE "GlobalRegions"
    ADD CONSTRAINT "PK_GlobalRegions" PRIMARY KEY ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230618135049_2', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_City_CityId";

ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_Country_CountryId";

ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_StreetModel_StreetId";

ALTER TABLE "CountryRegions" DROP CONSTRAINT "FK_CountryRegions_Country_CountryId";

ALTER TABLE "State" DROP CONSTRAINT "FK_State_Country_CountryId";

ALTER TABLE "StreetModel" DROP CONSTRAINT "FK_StreetModel_City_CityId";

ALTER TABLE "StreetModel" DROP CONSTRAINT "FK_StreetModel_Country_CountryId";

ALTER TABLE "TeamInvites" DROP CONSTRAINT "FK_TeamInvites_TeamModels_TeamId";

ALTER TABLE "TeamMembers" DROP CONSTRAINT "FK_TeamMembers_TeamModels_TeamModelId";

ALTER TABLE "TeamModels" DROP CONSTRAINT "FK_TeamModels_Users_OwnerId";

DROP TABLE "City";

DROP TABLE "Country";

ALTER TABLE "TeamModels" DROP CONSTRAINT "PK_TeamModels";

ALTER TABLE "StreetModel" DROP CONSTRAINT "PK_StreetModel";

ALTER TABLE "TeamModels" RENAME TO "Teams";

ALTER TABLE "StreetModel" RENAME TO "Streets";

ALTER
INDEX "IX_TeamModels_OwnerId" RENAME TO "IX_Teams_OwnerId";

ALTER
INDEX "IX_StreetModel_CountryId" RENAME TO "IX_Streets_CountryId";

ALTER
INDEX "IX_StreetModel_CityId" RENAME TO "IX_Streets_CityId";

ALTER TABLE "PhoneNumbers"
    ADD "CountryCode" text NOT NULL DEFAULT '';

ALTER TABLE "Teams"
    ADD CONSTRAINT "PK_Teams" PRIMARY KEY ("Id");

ALTER TABLE "Streets"
    ADD CONSTRAINT "PK_Streets" PRIMARY KEY ("Id");

CREATE TABLE "CountryModel"
(
    "Id"      integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"    text NOT NULL,
    "IsoCode" text NOT NULL,
    "CityId"  text NOT NULL,
    CONSTRAINT "PK_CountryModel" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"       text    NOT NULL,
    "CountryId"  integer NOT NULL,
    "PostalCode" integer NOT NULL,
    "StateId"    integer NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cities_CountryModel_CountryId" FOREIGN KEY ("CountryId") REFERENCES "CountryModel" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Cities_State_StateId" FOREIGN KEY ("StateId") REFERENCES "State" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Cities_CountryId" ON "Cities" ("CountryId");

CREATE INDEX "IX_Cities_StateId" ON "Cities" ("StateId");

ALTER TABLE "Addresses"
    ADD CONSTRAINT "FK_Addresses_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE;

ALTER TABLE "Addresses"
    ADD CONSTRAINT "FK_Addresses_CountryModel_CountryId" FOREIGN KEY ("CountryId") REFERENCES "CountryModel" ("Id") ON DELETE CASCADE;

ALTER TABLE "Addresses"
    ADD CONSTRAINT "FK_Addresses_Streets_StreetId" FOREIGN KEY ("StreetId") REFERENCES "Streets" ("Id") ON DELETE CASCADE;

ALTER TABLE "CountryRegions"
    ADD CONSTRAINT "FK_CountryRegions_CountryModel_CountryId" FOREIGN KEY ("CountryId") REFERENCES "CountryModel" ("Id") ON DELETE CASCADE;

ALTER TABLE "State"
    ADD CONSTRAINT "FK_State_CountryModel_CountryId" FOREIGN KEY ("CountryId") REFERENCES "CountryModel" ("Id") ON DELETE CASCADE;

ALTER TABLE "Streets"
    ADD CONSTRAINT "FK_Streets_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE;

ALTER TABLE "Streets"
    ADD CONSTRAINT "FK_Streets_Cities_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Cities" ("Id") ON DELETE CASCADE;

ALTER TABLE "TeamInvites"
    ADD CONSTRAINT "FK_TeamInvites_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE;

ALTER TABLE "TeamMembers"
    ADD CONSTRAINT "FK_TeamMembers_Teams_TeamModelId" FOREIGN KEY ("TeamModelId") REFERENCES "Teams" ("Id");

ALTER TABLE "Teams"
    ADD CONSTRAINT "FK_Teams_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230627124902_db fixes', '7.0.5');

COMMIT;

