// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Api.Client.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddressEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.CityEntity? City { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.CityEntity City { get; set; }
#endif
        /// <summary>The cityId property</summary>
        public int? CityId { get; set; }
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.CountryEntity? Country { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.CountryEntity Country { get; set; }
#endif
        /// <summary>The countryId property</summary>
        public int? CountryId { get; set; }
        /// <summary>The customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity? Customer { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity Customer { get; set; }
#endif
        /// <summary>The customerId property</summary>
        public int? CustomerId { get; set; }
        /// <summary>The floor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Floor { get; set; }
#nullable restore
#else
        public string Floor { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isPrimary property</summary>
        public bool? IsPrimary { get; set; }
        /// <summary>The latitude property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Latitude { get; set; }
#nullable restore
#else
        public string Latitude { get; set; }
#endif
        /// <summary>The longitude property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Longitude { get; set; }
#nullable restore
#else
        public string Longitude { get; set; }
#endif
        /// <summary>The postalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The street property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.StreetEntity? Street { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.StreetEntity Street { get; set; }
#endif
        /// <summary>The streetId property</summary>
        public int? StreetId { get; set; }
        /// <summary>The streetNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetNumber { get; set; }
#nullable restore
#else
        public string StreetNumber { get; set; }
#endif
        /// <summary>The tenant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity? Tenant { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity Tenant { get; set; }
#endif
        /// <summary>The tenantId property</summary>
        public int? TenantId { get; set; }
        /// <summary>The unitNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitNumber { get; set; }
#nullable restore
#else
        public string UnitNumber { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "city", n => { City = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CityEntity>(global::AppBlueprint.Api.Client.Sdk.Models.CityEntity.CreateFromDiscriminatorValue); } },
                { "cityId", n => { CityId = n.GetIntValue(); } },
                { "country", n => { Country = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CountryEntity>(global::AppBlueprint.Api.Client.Sdk.Models.CountryEntity.CreateFromDiscriminatorValue); } },
                { "countryId", n => { CountryId = n.GetIntValue(); } },
                { "customer", n => { Customer = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity>(global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity.CreateFromDiscriminatorValue); } },
                { "customerId", n => { CustomerId = n.GetIntValue(); } },
                { "floor", n => { Floor = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isPrimary", n => { IsPrimary = n.GetBoolValue(); } },
                { "latitude", n => { Latitude = n.GetStringValue(); } },
                { "longitude", n => { Longitude = n.GetStringValue(); } },
                { "postalCode", n => { PostalCode = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "street", n => { Street = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.StreetEntity>(global::AppBlueprint.Api.Client.Sdk.Models.StreetEntity.CreateFromDiscriminatorValue); } },
                { "streetId", n => { StreetId = n.GetIntValue(); } },
                { "streetNumber", n => { StreetNumber = n.GetStringValue(); } },
                { "tenant", n => { Tenant = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity>(global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity.CreateFromDiscriminatorValue); } },
                { "tenantId", n => { TenantId = n.GetIntValue(); } },
                { "unitNumber", n => { UnitNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CityEntity>("city", City);
            writer.WriteIntValue("cityId", CityId);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CountryEntity>("country", Country);
            writer.WriteIntValue("countryId", CountryId);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity>("customer", Customer);
            writer.WriteIntValue("customerId", CustomerId);
            writer.WriteStringValue("floor", Floor);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isPrimary", IsPrimary);
            writer.WriteStringValue("latitude", Latitude);
            writer.WriteStringValue("longitude", Longitude);
            writer.WriteStringValue("postalCode", PostalCode);
            writer.WriteStringValue("state", State);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.StreetEntity>("street", Street);
            writer.WriteIntValue("streetId", StreetId);
            writer.WriteStringValue("streetNumber", StreetNumber);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity>("tenant", Tenant);
            writer.WriteIntValue("tenantId", TenantId);
            writer.WriteStringValue("unitNumber", UnitNumber);
        }
    }
}
#pragma warning restore CS0618
