// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Api.Client.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EmailVerificationEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The expireAt property</summary>
        public DateTimeOffset? ExpireAt { get; set; }
        /// <summary>The hasBeenOpened property</summary>
        public bool? HasBeenOpened { get; set; }
        /// <summary>The hasBeenVerified property</summary>
        public bool? HasBeenVerified { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The lastUpdatedAt property</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>The token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "expireAt", n => { ExpireAt = n.GetDateTimeOffsetValue(); } },
                { "hasBeenOpened", n => { HasBeenOpened = n.GetBoolValue(); } },
                { "hasBeenVerified", n => { HasBeenVerified = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteDateTimeOffsetValue("expireAt", ExpireAt);
            writer.WriteBoolValue("hasBeenOpened", HasBeenOpened);
            writer.WriteBoolValue("hasBeenVerified", HasBeenVerified);
            writer.WriteIntValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteStringValue("token", Token);
        }
    }
}
#pragma warning restore CS0618
