// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Api.Client.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TeamMemberEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The alias property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity? Team { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity Team { get; set; }
#endif
        /// <summary>The teamId property</summary>
        public int? TeamId { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.UserEntity? User { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.UserEntity User { get; set; }
#endif
        /// <summary>The userId property</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Models.TeamMemberEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Api.Client.Sdk.Models.TeamMemberEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Api.Client.Sdk.Models.TeamMemberEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "team", n => { Team = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity>(global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity.CreateFromDiscriminatorValue); } },
                { "teamId", n => { TeamId = n.GetIntValue(); } },
                { "user", n => { User = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.UserEntity>(global::AppBlueprint.Api.Client.Sdk.Models.UserEntity.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity>("team", Team);
            writer.WriteIntValue("teamId", TeamId);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.UserEntity>("user", User);
            writer.WriteIntValue("userId", UserId);
        }
    }
}
#pragma warning restore CS0618
