// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Api.Client.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TenantEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contactPersons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.ContactPersonEntity>? ContactPersons { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.ContactPersonEntity> ContactPersons { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity? Customer { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity Customer { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The isPrimary property</summary>
        public bool? IsPrimary { get; set; }
        /// <summary>The lastUpdatedAt property</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The teams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity>? Teams { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity> Teams { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.UserEntity>? Users { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.UserEntity> Users { get; set; }
#endif
        /// <summary>The vatNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VatNumber { get; set; }
#nullable restore
#else
        public string VatNumber { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contactPersons", n => { ContactPersons = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.ContactPersonEntity>(global::AppBlueprint.Api.Client.Sdk.Models.ContactPersonEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customer", n => { Customer = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity>(global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isPrimary", n => { IsPrimary = n.GetBoolValue(); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "teams", n => { Teams = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity>(global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "users", n => { Users = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.UserEntity>(global::AppBlueprint.Api.Client.Sdk.Models.UserEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "vatNumber", n => { VatNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.ContactPersonEntity>("contactPersons", ContactPersons);
            writer.WriteStringValue("country", Country);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.CustomerEntity>("customer", Customer);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("email", Email);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isPrimary", IsPrimary);
            writer.WriteDateTimeOffsetValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("phone", Phone);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.TeamEntity>("teams", Teams);
            writer.WriteStringValue("type", Type);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.UserEntity>("users", Users);
            writer.WriteStringValue("vatNumber", VatNumber);
        }
    }
}
#pragma warning restore CS0618
