// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AppBlueprint.Api.Client.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserEntity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity>? Addresses { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity> Addresses { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The emailAddresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.EmailAddressEntity>? EmailAddresses { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.EmailAddressEntity> EmailAddresses { get; set; }
#endif
        /// <summary>The emailVerifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity>? EmailVerifications { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity> EmailVerifications { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The lastLogin property</summary>
        public DateTimeOffset? LastLogin { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.ProfileEntity? Profile { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.ProfileEntity Profile { get; set; }
#endif
        /// <summary>The referralInvitations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.EmailInviteEntity>? ReferralInvitations { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.EmailInviteEntity> ReferralInvitations { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AppBlueprint.Api.Client.Sdk.Models.RoleEntity>? Roles { get; set; }
#nullable restore
#else
        public List<global::AppBlueprint.Api.Client.Sdk.Models.RoleEntity> Roles { get; set; }
#endif
        /// <summary>The tenant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity? Tenant { get; set; }
#nullable restore
#else
        public global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity Tenant { get; set; }
#endif
        /// <summary>The userName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Models.UserEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AppBlueprint.Api.Client.Sdk.Models.UserEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AppBlueprint.Api.Client.Sdk.Models.UserEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addresses", n => { Addresses = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity>(global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "emailAddresses", n => { EmailAddresses = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.EmailAddressEntity>(global::AppBlueprint.Api.Client.Sdk.Models.EmailAddressEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "emailVerifications", n => { EmailVerifications = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity>(global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "lastLogin", n => { LastLogin = n.GetDateTimeOffsetValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "profile", n => { Profile = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.ProfileEntity>(global::AppBlueprint.Api.Client.Sdk.Models.ProfileEntity.CreateFromDiscriminatorValue); } },
                { "referralInvitations", n => { ReferralInvitations = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.EmailInviteEntity>(global::AppBlueprint.Api.Client.Sdk.Models.EmailInviteEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "roles", n => { Roles = n.GetCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.RoleEntity>(global::AppBlueprint.Api.Client.Sdk.Models.RoleEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tenant", n => { Tenant = n.GetObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity>(global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity.CreateFromDiscriminatorValue); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.AddressEntity>("addresses", Addresses);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("email", Email);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.EmailAddressEntity>("emailAddresses", EmailAddresses);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.EmailVerificationEntity>("emailVerifications", EmailVerifications);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteDateTimeOffsetValue("lastLogin", LastLogin);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.ProfileEntity>("profile", Profile);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.EmailInviteEntity>("referralInvitations", ReferralInvitations);
            writer.WriteCollectionOfObjectValues<global::AppBlueprint.Api.Client.Sdk.Models.RoleEntity>("roles", Roles);
            writer.WriteObjectValue<global::AppBlueprint.Api.Client.Sdk.Models.TenantEntity>("tenant", Tenant);
            writer.WriteStringValue("userName", UserName);
        }
    }
}
#pragma warning restore CS0618
