// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Account.CreateAccount;
using AppBlueprint.Api.Client.Sdk.Api.V1.Account.DeleteAccount;
using AppBlueprint.Api.Client.Sdk.Api.V1.Account.GetAccounts;
using AppBlueprint.Api.Client.Sdk.Api.V1.Account.UpdateAccount;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Account
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateAccount property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.CreateAccount.CreateAccountRequestBuilder CreateAccount
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.CreateAccount.CreateAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteAccount property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.DeleteAccount.DeleteAccountRequestBuilder DeleteAccount
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.DeleteAccount.DeleteAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAccounts property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.GetAccounts.GetAccountsRequestBuilder GetAccounts
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.GetAccounts.GetAccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateAccount property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.UpdateAccount.UpdateAccountRequestBuilder UpdateAccount
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.UpdateAccount.UpdateAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/account", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/account", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
