// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.CreateTenant;
using AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.DeleteTenant;
using AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.GetTenant;
using AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.GetTenants;
using AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.UpdateTenant;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Tenant
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\tenant
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TenantRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateTenant property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.CreateTenant.CreateTenantRequestBuilder CreateTenant
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.CreateTenant.CreateTenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeleteTenant property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.DeleteTenant.DeleteTenantRequestBuilder DeleteTenant
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.DeleteTenant.DeleteTenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetTenant property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.GetTenant.GetTenantRequestBuilder GetTenant
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.GetTenant.GetTenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetTenants property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.GetTenants.GetTenantsRequestBuilder GetTenants
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.GetTenants.GetTenantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateTenant property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.UpdateTenant.UpdateTenantRequestBuilder UpdateTenant
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.UpdateTenant.UpdateTenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/tenant", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/tenant", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
