# Deprecated: use per-project Dockerfiles instead.
# Web:  DeploymentManager/DeploymentManager.Web/Dockerfile
# API:  DeploymentManager/DeploymentManager.ApiService/Dockerfile
#
# Both require build context = Code/ (parent of DeploymentManager/ and AppBlueprint/)
# docker build -f DeploymentManager/DeploymentManager.Web/Dockerfile -t deploymentmanager-web .
FROM scratch
