#:schema node_modules/wrangler/config-schema.json
name = "deployment-manager"
main = "Cloudflare-Workers/src/index.ts"
compatibility_date = "2026-06-22"


[observability]
enabled = true

[[durable_objects.bindings]]
name = "WEB_CONTAINER"
class_name = "Web"

[[durable_objects.bindings]]
name = "API_CONTAINER"
class_name = "Api"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Web", "Api"]

[[containers]]
class_name = "Web"
image = "DeploymentManager.Web/Dockerfile"
instance_type = "lite"
image_build_context = "../.."

[[containers]]
class_name = "Api"
image = "DeploymentManager.ApiService/Dockerfile"
instance_type = "lite"
image_build_context = "../.."
