// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.DeleteAuditLog;
using AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.GetAuditLog;
using AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.GetAuditLogs;
using AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.UpdateAuditLog;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\auditlog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditlogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The DeleteAuditLog property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.DeleteAuditLog.DeleteAuditLogRequestBuilder DeleteAuditLog
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.DeleteAuditLog.DeleteAuditLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAuditLog property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.GetAuditLog.GetAuditLogRequestBuilder GetAuditLog
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.GetAuditLog.GetAuditLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAuditLogs property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.GetAuditLogs.GetAuditLogsRequestBuilder GetAuditLogs
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.GetAuditLogs.GetAuditLogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateAuditLog property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.UpdateAuditLog.UpdateAuditLogRequestBuilder UpdateAuditLog
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.UpdateAuditLog.UpdateAuditLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.AuditlogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditlogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/auditlog", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.AuditlogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditlogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/auditlog", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
