// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\admin\DeleteAdminAccount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteAdminAccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AppBlueprint.Api.Client.Sdk.api.v1.admin.DeleteAdminAccount.item collection</summary>
        /// <param name="position">Admin account ID.</param>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item.DeleteAdminAccountItemRequestBuilder"/></returns>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item.DeleteAdminAccountItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item.DeleteAdminAccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AppBlueprint.Api.Client.Sdk.api.v1.admin.DeleteAdminAccount.item collection</summary>
        /// <param name="position">Admin account ID.</param>
        /// <returns>A <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item.DeleteAdminAccountItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item.DeleteAdminAccountItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.Item.DeleteAdminAccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.DeleteAdminAccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteAdminAccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/admin/DeleteAdminAccount", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.DeleteAdminAccount.DeleteAdminAccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteAdminAccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/admin/DeleteAdminAccount", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
