// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.Login;
using AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.Register;
using AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.ResetPassword;
using AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.SetupMFA;
using AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.VerifyMFA;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1.Authentication
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\authentication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthenticationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Login property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.Login.LoginRequestBuilder Login
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Register property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.Register.RegisterRequestBuilder Register
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ResetPassword property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetupMFA property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.SetupMFA.SetupMFARequestBuilder SetupMFA
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.SetupMFA.SetupMFARequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The VerifyMFA property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.VerifyMFA.VerifyMFARequestBuilder VerifyMFA
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.VerifyMFA.VerifyMFARequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.AuthenticationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthenticationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/authentication", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.AuthenticationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthenticationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/authentication", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
