// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.Files;
using AppBlueprint.Api.Client.Sdk.Api.Integrations;
using AppBlueprint.Api.Client.Sdk.Api.Roles;
using AppBlueprint.Api.Client.Sdk.Api.Subscriptions;
using AppBlueprint.Api.Client.Sdk.Api.V1;
using AppBlueprint.Api.Client.Sdk.Api.V2;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Files property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Files.FilesRequestBuilder Files
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integrations property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Integrations.IntegrationsRequestBuilder Integrations
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Integrations.IntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Roles.RolesRequestBuilder Roles
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptions property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.Subscriptions.SubscriptionsRequestBuilder Subscriptions
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v1 property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.V1RequestBuilder V1
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V2.V2RequestBuilder V2
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
