name: Create diagram
on:
  workflow_dispatch: {}
#  push:
#    branches:
#      - main
jobs:
  get_data:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
