// <auto-generated/>
#pragma warning disable CS0618
using AppBlueprint.Api.Client.Sdk.Api.V1.Account;
using AppBlueprint.Api.Client.Sdk.Api.V1.Admin;
using AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys;
using AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog;
using AppBlueprint.Api.Client.Sdk.Api.V1.Authentication;
using AppBlueprint.Api.Client.Sdk.Api.V1.DataExports;
using AppBlueprint.Api.Client.Sdk.Api.V1.Demos;
using AppBlueprint.Api.Client.Sdk.Api.V1.Organization;
using AppBlueprint.Api.Client.Sdk.Api.V1.Team;
using AppBlueprint.Api.Client.Sdk.Api.V1.Tenant;
using AppBlueprint.Api.Client.Sdk.Api.V1.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AppBlueprint.Api.Client.Sdk.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.AccountRequestBuilder Account
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The admin property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.AdminRequestBuilder Admin
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apiKeys property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auditlog property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.AuditlogRequestBuilder Auditlog
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Auditlog.AuditlogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The authentication property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.AuthenticationRequestBuilder Authentication
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Authentication.AuthenticationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataExports property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DataExportsRequestBuilder DataExports
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.DataExports.DataExportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The demos property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Demos.DemosRequestBuilder Demos
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Demos.DemosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organization property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.OrganizationRequestBuilder Organization
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Organization.OrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.TeamRequestBuilder Team
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Team.TeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenant property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.TenantRequestBuilder Tenant
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Tenant.TenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::AppBlueprint.Api.Client.Sdk.Api.V1.Users.UsersRequestBuilder Users
        {
            get => new global::AppBlueprint.Api.Client.Sdk.Api.V1.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AppBlueprint.Api.Client.Sdk.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
